# Makefile generated by BNFC.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestEmm

# Rules for building the parser.

AbsEmm.hs LexEmm.x ParEmm.y PrintEmm.hs TestEmm.hs : emm.cf
	bnfc --haskell emm.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestEmm : AbsEmm.hs LexEmm.hs ParEmm.hs PrintEmm.hs TestEmm.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsEmm.hs AbsEmm.hs.bak ComposOp.hs ComposOp.hs.bak DocEmm.txt DocEmm.txt.bak ErrM.hs ErrM.hs.bak LayoutEmm.hs LayoutEmm.hs.bak LexEmm.x LexEmm.x.bak ParEmm.y ParEmm.y.bak PrintEmm.hs PrintEmm.hs.bak SkelEmm.hs SkelEmm.hs.bak TestEmm.hs TestEmm.hs.bak XMLEmm.hs XMLEmm.hs.bak ASTEmm.agda ASTEmm.agda.bak ParserEmm.agda ParserEmm.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak emm.dtd emm.dtd.bak TestEmm LexEmm.hs ParEmm.hs ParEmm.info ParDataEmm.hs Makefile


# EOF
