{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintEmm.
--   Generated by the BNF converter.

module PrintEmm where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsEmm

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsEmm.Ident where
  prt _ (AbsEmm.Ident i) = doc $ showString i

instance Print AbsEmm.Program where
  prt i = \case
    AbsEmm.Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print AbsEmm.TopDef where
  prt i = \case
    AbsEmm.TopDef decl -> prPrec i 0 (concatD [prt 0 decl])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsEmm.TopDef] where
  prt = prtList

instance Print AbsEmm.Decl where
  prt i = \case
    AbsEmm.Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    AbsEmm.FnDecl type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print AbsEmm.Arg where
  prt i = \case
    AbsEmm.Arg type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    AbsEmm.ArgRef type_ id_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&"), prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsEmm.Arg] where
  prt = prtList

instance Print AbsEmm.Item where
  prt i = \case
    AbsEmm.NoInit id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsEmm.Init id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])
    AbsEmm.Array id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]")])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsEmm.Item] where
  prt = prtList

instance Print AbsEmm.Block where
  prt i = \case
    AbsEmm.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsEmm.Stmt] where
  prt = prtList

instance Print AbsEmm.Stmt where
  prt i = \case
    AbsEmm.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsEmm.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsEmm.SDecl decl -> prPrec i 0 (concatD [prt 0 decl])
    AbsEmm.Ass id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsEmm.AssArr id_ expr1 expr2 -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr1, doc (showString "]"), doc (showString "="), prt 0 expr2, doc (showString ";")])
    AbsEmm.Incr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    AbsEmm.IncrArr id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]"), doc (showString "++"), doc (showString ";")])
    AbsEmm.Decr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    AbsEmm.DecrArr id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]"), doc (showString "--"), doc (showString ";")])
    AbsEmm.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsEmm.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsEmm.Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsEmm.CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsEmm.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsEmm.Brk -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    AbsEmm.Cnt -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])
    AbsEmm.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsEmm.Type where
  prt i = \case
    AbsEmm.Int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsEmm.Str -> prPrec i 0 (concatD [doc (showString "string")])
    AbsEmm.Bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsEmm.Void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsEmm.Fun type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsEmm.Type] where
  prt = prtList

instance Print AbsEmm.Expr where
  prt i = \case
    AbsEmm.EArr id_ expr -> prPrec i 6 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]")])
    AbsEmm.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsEmm.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    AbsEmm.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    AbsEmm.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    AbsEmm.EApp id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsEmm.EString str -> prPrec i 6 (concatD [prt 0 str])
    AbsEmm.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsEmm.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsEmm.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsEmm.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsEmm.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsEmm.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsEmm.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsEmm.Expr] where
  prt = prtList

instance Print AbsEmm.AddOp where
  prt i = \case
    AbsEmm.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsEmm.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsEmm.MulOp where
  prt i = \case
    AbsEmm.Times -> prPrec i 0 (concatD [doc (showString "*")])
    AbsEmm.Div -> prPrec i 0 (concatD [doc (showString "/")])
    AbsEmm.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AbsEmm.RelOp where
  prt i = \case
    AbsEmm.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsEmm.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsEmm.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsEmm.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsEmm.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsEmm.NE -> prPrec i 0 (concatD [doc (showString "!=")])

